// AUTOGENERATED ON 2026-02-17T20:44:40.195148198Z

export type ResumeUpdater =
  | ResumeUpdater.AddContactItem
  | ResumeUpdater.AddSection
  | ResumeUpdater.MoveContactItem
  | ResumeUpdater.MoveSection
  | ResumeUpdater.RemoveContactItem
  | ResumeUpdater.RemoveSection
  | ResumeUpdater.UpdateContactItem
  | ResumeUpdater.UpdateName
  | ResumeUpdater.UpdateSection
  | ResumeUpdater.UpdateSettings
  | ResumeUpdater.UpdateSummary;

export namespace ResumeUpdater {
  export enum Type {
    AddContactItem = "me.kthomas.resume.ResumeUpdater.AddContactItem",
    AddSection = "me.kthomas.resume.ResumeUpdater.AddSection",
    MoveContactItem = "me.kthomas.resume.ResumeUpdater.MoveContactItem",
    MoveSection = "me.kthomas.resume.ResumeUpdater.MoveSection",
    RemoveContactItem = "me.kthomas.resume.ResumeUpdater.RemoveContactItem",
    RemoveSection = "me.kthomas.resume.ResumeUpdater.RemoveSection",
    UpdateContactItem = "me.kthomas.resume.ResumeUpdater.UpdateContactItem",
    UpdateName = "me.kthomas.resume.ResumeUpdater.UpdateName",
    UpdateSection = "me.kthomas.resume.ResumeUpdater.UpdateSection",
    UpdateSettings = "me.kthomas.resume.ResumeUpdater.UpdateSettings",
    UpdateSummary = "me.kthomas.resume.ResumeUpdater.UpdateSummary",
  }
  
  export interface AddContactItem {
    type: ResumeUpdater.Type.AddContactItem;
    item: ResumeContactItem;
  }
  
  export interface AddSection {
    type: ResumeUpdater.Type.AddSection;
    section: ResumeSection;
  }
  
  export interface MoveContactItem {
    type: ResumeUpdater.Type.MoveContactItem;
    oldIndex: number;
    newIndex: number;
  }
  
  export interface MoveSection {
    type: ResumeUpdater.Type.MoveSection;
    oldIndex: number;
    newIndex: number;
  }
  
  export interface RemoveContactItem {
    type: ResumeUpdater.Type.RemoveContactItem;
    index: number;
  }
  
  export interface RemoveSection {
    type: ResumeUpdater.Type.RemoveSection;
    index: number;
  }
  
  export interface UpdateContactItem {
    type: ResumeUpdater.Type.UpdateContactItem;
    index: number;
    item: ResumeContactItem;
  }
  
  export interface UpdateName {
    type: ResumeUpdater.Type.UpdateName;
    newName: string;
  }
  
  export interface UpdateSection {
    type: ResumeUpdater.Type.UpdateSection;
    index: number;
    updater: SectionUpdater;
  }
  
  export interface UpdateSettings {
    type: ResumeUpdater.Type.UpdateSettings;
    updater: SettingsUpdater;
  }
  
  export interface UpdateSummary {
    type: ResumeUpdater.Type.UpdateSummary;
    newSummary: string;
  }
}

export interface ResumeContactItem {
  icon: ResumeContactIcon;
  value: string;
}

export interface ResumeSection {
  title: string;
  contentItems: ResumeContent[];
}

export type SectionUpdater =
  | SectionUpdater.AddContent
  | SectionUpdater.MoveContent
  | SectionUpdater.RemoveContent
  | SectionUpdater.UpdateContent
  | SectionUpdater.UpdateTitle;

export namespace SectionUpdater {
  export enum Type {
    AddContent = "me.kthomas.resume.SectionUpdater.AddContent",
    MoveContent = "me.kthomas.resume.SectionUpdater.MoveContent",
    RemoveContent = "me.kthomas.resume.SectionUpdater.RemoveContent",
    UpdateContent = "me.kthomas.resume.SectionUpdater.UpdateContent",
    UpdateTitle = "me.kthomas.resume.SectionUpdater.UpdateTitle",
  }
  
  export interface AddContent {
    type: SectionUpdater.Type.AddContent;
    content: ResumeContent;
  }
  
  export interface MoveContent {
    type: SectionUpdater.Type.MoveContent;
    oldIndex: number;
    newIndex: number;
  }
  
  export interface RemoveContent {
    type: SectionUpdater.Type.RemoveContent;
    index: number;
  }
  
  export interface UpdateContent {
    type: SectionUpdater.Type.UpdateContent;
    index: number;
    updater: ContentUpdater;
  }
  
  export interface UpdateTitle {
    type: SectionUpdater.Type.UpdateTitle;
    newTitle: string;
  }
}

export type SettingsUpdater =
  | SettingsUpdater.UpdateBaseFontSize;

export namespace SettingsUpdater {
  export enum Type {
    UpdateBaseFontSize = "me.kthomas.resume.SettingsUpdater.UpdateBaseFontSize",
  }
  
  export interface UpdateBaseFontSize {
    type: SettingsUpdater.Type.UpdateBaseFontSize;
    size: number;
  }
}

export enum ResumeContactIcon {
  Email = "Email",
  Phone = "Phone",
  Website = "Website",
  Github = "Github",
  LinkedIn = "LinkedIn",
}

export type ResumeContent =
  | ResumeContent.SectionItem
  | ResumeContent.TextContent;

export namespace ResumeContent {
  export enum Type {
    SectionItem = "me.kthomas.resume.ResumeContent.SectionItem",
    TextContent = "me.kthomas.resume.ResumeContent.TextContent",
  }
  
  export interface SectionItem {
    type: ResumeContent.Type.SectionItem;
    item: ResumeSectionItem;
  }
  
  export interface TextContent {
    type: ResumeContent.Type.TextContent;
    text: ResumeText;
  }
}

export type ContentUpdater =
  | ContentUpdater.AddBulletPoint
  | ContentUpdater.RemoveBulletPoint
  | ContentUpdater.UpdateBulletPoints
  | ContentUpdater.UpdateColumnItem
  | ContentUpdater.UpdateColumns
  | ContentUpdater.UpdateParagraph
  | ContentUpdater.UpdateSectionItem;

export namespace ContentUpdater {
  export enum Type {
    AddBulletPoint = "me.kthomas.resume.ContentUpdater.AddBulletPoint",
    RemoveBulletPoint = "me.kthomas.resume.ContentUpdater.RemoveBulletPoint",
    UpdateBulletPoints = "me.kthomas.resume.ContentUpdater.UpdateBulletPoints",
    UpdateColumnItem = "me.kthomas.resume.ContentUpdater.UpdateColumnItem",
    UpdateColumns = "me.kthomas.resume.ContentUpdater.UpdateColumns",
    UpdateParagraph = "me.kthomas.resume.ContentUpdater.UpdateParagraph",
    UpdateSectionItem = "me.kthomas.resume.ContentUpdater.UpdateSectionItem",
  }
  
  export interface AddBulletPoint {
    type: ContentUpdater.Type.AddBulletPoint;
    item: string;
  }
  
  export interface RemoveBulletPoint {
    type: ContentUpdater.Type.RemoveBulletPoint;
    index: number;
  }
  
  export interface UpdateBulletPoints {
    type: ContentUpdater.Type.UpdateBulletPoints;
    items?: string[] | null;
    columns?: number | null;
  }
  
  export interface UpdateColumnItem {
    type: ContentUpdater.Type.UpdateColumnItem;
    index: number;
    updater: ColumnItemUpdater;
  }
  
  export interface UpdateColumns {
    type: ContentUpdater.Type.UpdateColumns;
    items: ColumnItem[];
  }
  
  export interface UpdateParagraph {
    type: ContentUpdater.Type.UpdateParagraph;
    text: string;
  }
  
  export interface UpdateSectionItem {
    type: ContentUpdater.Type.UpdateSectionItem;
    updater: SectionItemUpdater;
  }
}

export interface ResumeSectionItem {
  leftLabel: string | null;
  centerLabel: string | null;
  rightLabel: string | null;
  contentItems: TextContent[];
}

export type ResumeText =
  | ResumeText.BulletPoints
  | ResumeText.Columns
  | ResumeText.Paragraph;

export namespace ResumeText {
  export enum Type {
    BulletPoints = "me.kthomas.resume.ResumeText.BulletPoints",
    Columns = "me.kthomas.resume.ResumeText.Columns",
    Paragraph = "me.kthomas.resume.ResumeText.Paragraph",
  }
  
  export interface BulletPoints {
    type: ResumeText.Type.BulletPoints;
    items: string[];
    columns: number;
  }
  
  export interface Columns {
    type: ResumeText.Type.Columns;
    items: ColumnItem[];
  }
  
  export interface Paragraph {
    type: ResumeText.Type.Paragraph;
    text: string;
  }
}

export type ColumnItemUpdater =
  | ColumnItemUpdater.AddItem
  | ColumnItemUpdater.RemoveItem
  | ColumnItemUpdater.UpdateItems
  | ColumnItemUpdater.UpdateLabel;

export namespace ColumnItemUpdater {
  export enum Type {
    AddItem = "me.kthomas.resume.ColumnItemUpdater.AddItem",
    RemoveItem = "me.kthomas.resume.ColumnItemUpdater.RemoveItem",
    UpdateItems = "me.kthomas.resume.ColumnItemUpdater.UpdateItems",
    UpdateLabel = "me.kthomas.resume.ColumnItemUpdater.UpdateLabel",
  }
  
  export interface AddItem {
    type: ColumnItemUpdater.Type.AddItem;
    text: string;
  }
  
  export interface RemoveItem {
    type: ColumnItemUpdater.Type.RemoveItem;
    index: number;
  }
  
  export interface UpdateItems {
    type: ColumnItemUpdater.Type.UpdateItems;
    items: string[];
  }
  
  export interface UpdateLabel {
    type: ColumnItemUpdater.Type.UpdateLabel;
    label: string;
  }
}

export type SectionItemUpdater =
  | SectionItemUpdater.AddContent
  | SectionItemUpdater.MoveContent
  | SectionItemUpdater.RemoveContent
  | SectionItemUpdater.UpdateContent
  | SectionItemUpdater.UpdateLabels;

export namespace SectionItemUpdater {
  export enum Type {
    AddContent = "me.kthomas.resume.SectionItemUpdater.AddContent",
    MoveContent = "me.kthomas.resume.SectionItemUpdater.MoveContent",
    RemoveContent = "me.kthomas.resume.SectionItemUpdater.RemoveContent",
    UpdateContent = "me.kthomas.resume.SectionItemUpdater.UpdateContent",
    UpdateLabels = "me.kthomas.resume.SectionItemUpdater.UpdateLabels",
  }
  
  export interface AddContent {
    type: SectionItemUpdater.Type.AddContent;
    content: ResumeContent;
  }
  
  export interface MoveContent {
    type: SectionItemUpdater.Type.MoveContent;
    oldIndex: number;
    newIndex: number;
  }
  
  export interface RemoveContent {
    type: SectionItemUpdater.Type.RemoveContent;
    index: number;
  }
  
  export interface UpdateContent {
    type: SectionItemUpdater.Type.UpdateContent;
    index: number;
    updater: ContentUpdater;
  }
  
  export interface UpdateLabels {
    type: SectionItemUpdater.Type.UpdateLabels;
    leftLabel?: string | null;
    centerLabel?: string | null;
    rightLabel?: string | null;
    useNull?: boolean;
  }
}

export interface ColumnItem {
  label: string;
  items: string[];
}

export interface TextContent {
  text: ResumeText;
}